# Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

# Loading Dataset

In [2]:
df = pd.read_csv('../Data/hotel_bookings 2.csv')

# Exploratory Data Analysis and Data Cleaning

In [3]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,1/7/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,1/7/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2/7/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2/7/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,3/7/2015

In [4]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,6/9/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,7/9/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,7/9/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,7/9/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,7/9/2017

In [5]:
df.shape

(119390, 32)

In [6]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

#### Change Datatype str to datetime

In [8]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], dayfirst = True)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(16), str(11)
memory usage: 29.1 MB

In [ ]:
df.describe(include = 'object')

### Extract object with their respacted unique values

In [ ]:
for col in df.describe(include = 'object'):
    print(col)
    print(df[col].unique())
    print('-'*70)

### checking missing values

In [ ]:
df.isnull().sum()

### Removing missing values

In [ ]:
df.drop(['agent','company'], axis = 1, inplace = True)
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

In [ ]:
df.shape

### Summary Statistic for Numeral Columns

In [ ]:
df.describe()

### Ploting / Detacting Outlier - in adr

In [ ]:
df['adr'].plot(kind = 'box')

### Removing Outlier

In [ ]:
df = df[df['adr'] < 5000]

In [ ]:
df.describe()

# Data Analysis and Visualization

## Step 1 — Overall Cancellation Rate

In [ ]:
print(df['is_canceled'].value_counts())

### Calculate the cancellation rate

In [ ]:
# print(df['is_canceled'].value_counts(normalize = True))

cancellation_rate = df['is_canceled'].mean() * 100
print(f"Overall cancellation rate: {cancellation_rate:.2f}%")

### Creating a small Summary Table

In [ ]:
cancellation_summary = (
    df["is_canceled"]
    .value_counts()
    .rename(index={0: "Not Canceled", 1: "Canceled"})
    .reset_index()
)

cancellation_summary.columns = ["Booking Status", "Bookings"]

cancellation_summary["Percentage"] = (
    cancellation_summary["Bookings"] / len(df) * 100
)

cancellation_summary

In [ ]:

status_counts = df["is_canceled"].value_counts()
labels = ["Not Canceled", "Canceled"]

plt.figure(figsize=(7, 7) )
plt.pie(
    status_counts,
    labels=labels,
    autopct="%1.2f%%",
    startangle=90,
    wedgeprops={"width": 0.4},
    colors = light_palette[::3]
)

plt.title("Overall Hotel Booking Cancellation Rate")
plt.show()

### Finding

**Finding:** The overall cancellation rate is 37.04%, meaning approximately 37.13% of bookings in the dataset were canceled, while 62.87% were not canceled.

### Business interpretation

**Business Interpretation:** A cancellation rate of approximately 37.13% represents a substantial proportion of bookings that may affect room occupancy and expected revenue. Therefore, identifying the characteristics associated with canceled bookings is important for developing targeted cancellation-reduction strategies.

### Next step

**Next Step:** To identify the key factors associated with cancellations, the analysis will examine cancellation rates across hotel type, ADR, lead time, deposit type, market segment, seasonality, and other booking characteristics.

## Step 2 — cancellation rate by hotel

In [ ]:
df[['hotel','is_canceled']].head()

In [ ]:
cancellation_rate_by_hotel = (
    df.groupby('hotel')['is_canceled']
    .mean()
    .mul(100)
    .round(2)
    .reset_index(name = 'cancellation_rate')
)
# cancellation_rate_by_hotel

In [ ]:
cancellation_rate_by_hotel.columns = ['Hotel Type', 'Cancellation Rate %']
cancellation_rate_by_hotel

### Calculate the difference

In [ ]:
rate_difference = (
    cancellation_rate_by_hotel['Cancellation Rate %'].max()
    -cancellation_rate_by_hotel['Cancellation Rate %'].min() 
)
rate_difference # 13.73 percentage points higher

In [ ]:
# Prepare data
status_counts = df.groupby("hotel")["is_canceled"].mean() * 100
labels = status_counts.index  

light_palette = ["#F3CFCE", "#F2B1B1", "#F09393", "#F77979", "#ED5757"]

# Create horizontal bar chart
fig, ax = plt.subplots(figsize=(6,4))
bars = ax.barh(labels, status_counts, color=light_palette[::3][::-1])

ax.bar_label(bars, fmt="%.1f%%", padding=3)
ax.set_xlim(0, max(status_counts) * 1.2)

plt.title('Cancellation Rate by Hotel')
plt.tight_layout()
plt.show()

## Step 3 — Cancellation Rate by Lead Time

In [ ]:
df[['lead_time','is_canceled']].head()

### Create the Lead Time Groups

In [ ]:
bins = [-1, 7, 30, 90, 180 , float('inf')]

labels = [
    '0 - 7 days',
    '8 - 30 days',
    '31 - 90 days',
    '91 - 180 days',
    '180+ days'
]

df['lead_time_groups'] = pd.cut(
    df['lead_time'],
    bins = bins,
    labels = labels
)

### Calculate Cancellation Rate by lead time

In [ ]:
lead_time_summary = (
    df.groupby('lead_time_groups',observed=False)['is_canceled']
        .mean()
        .mul(100)
        .round(2)
        .reset_index(name = 'cancellation_rate')
)
lead_time_summary

### Calculate the Difference

In [ ]:
lead_time_difference = (
    lead_time_summary['cancellation_rate'].max()
    - lead_time_summary['cancellation_rate'].min()
)
lead_time_difference

### Cancellation Rate by lead time

In [ ]:
plt.figure(figsize = (10, 6))
ax = sns.barplot(
            data = lead_time_summary,
            x = 'lead_time_groups',
            y = 'cancellation_rate',
            palette= sns.color_palette(light_palette, n_colors=len(lead_time_summary)) 
        )
for container in ax.containers:
    ax.bar_label(container, fmt="%.1f%%")
    
plt.title('Cancellation Rate by Lead Time')
plt.xlabel('Lead time')
plt.ylabel('Cancellation Rate %')

plt.tight_layout()
plt.show()

#### Interpretation

Cancellation rate increases consistently as lead time increases. Bookings made **0–7 days before arrival have a cancellation rate of 9.7%**, while bookings made **181+ days in advance have a cancellation rate of 57.0%**. This represents a difference of **47.31 percentage points**.

The results indicate a strong positive association between longer lead times and booking cancellations. Customers who book significantly further in advance appear to have a higher likelihood of canceling their reservations.

From a business perspective, hotels should pay particular attention to long-lead bookings because they represent a higher cancellation-risk segment. However, this analysis identifies an association rather than proving that longer lead time directly causes cancellations.

## Step 4 — Cancellation Rate by Deposit Type

#### Business Question
How does cancellation rate vary by deposit type?

### Analysis
1. Group bookings by deposit type

#### Deposit Type Cancellation Summary Table

In [ ]:
deposit_cancellation = (
    df.groupby('deposit_type')['is_canceled']
    .agg(
          total_bookings='count',
          canceled_bookings='sum',
          cancellation_rate='mean'
      )
    .reset_index()
)
deposit_cancellation['cancellation_rate'] = (
    deposit_cancellation['cancellation_rate'] * 100
).round(2)

deposit_cancellation = deposit_cancellation.sort_values(
                        by = 'cancellation_rate'
)

deposit_cancellation

In [ ]:
deposit_cancellation.style.format({
    'cancellation_rate': '{:.2f}%'
})

### Cancellation Rate by Deposit Type

In [ ]:

plt.figure(figsize=(8, 5))

ax = sns.barplot(
    data=deposit_cancellation,
    x='deposit_type',
    y='cancellation_rate',
    palette= sns.color_palette( light_palette , n_colors=len(deposit_cancellation)) 
)

plt.title('Cancellation Rate by Deposit Type')
plt.xlabel('Deposit Type')
plt.ylabel('Cancellation Rate (%)')
plt.ylim(0, 110)

for container in ax.containers:
    ax.bar_label(
        container,
        fmt='%.1f%%',
        padding=3
    )

plt.show()

### Investigate the unusually high Non Refund cancellation rate

#### step 1 : Check the sample size

In [ ]:
non_refund_check = (
    df.groupby('deposit_type')['is_canceled']
     .agg(Booking = 'count',
         Cancelled = 'sum', 
         cancellation_rate = 'mean')
      .reset_index()
)

non_refund_check['cancellation_rate'] = (
    non_refund_check['cancellation_rate'] * 100
).round(2)

non_refund_check

#### step 2: Look directly at the Non Refund bookings

In [24]:
non_refund = df[df['deposit_type'] == 'Non Refund']

non_refund['is_canceled'].value_counts()

is_canceled
1    14479
0       93
Name: count, dtype: int64

#### step 3: Compare Non Refund cancellation rate by hotel

In [ ]:
non_refund_hotel = (
    df[df['deposit_type'] == 'Non Refund']
    .groupby('hotel')['is_canceled']
    .agg(Booking = 'count',
         Cancelled = 'sum', 
         cancellation_rate = 'mean')
    .reset_index()
)

non_refund_hotel['cancellation_rate'] = (
    non_refund_hotel['cancellation_rate'] * 100
).round(2)

non_refund_hotel

#### step 4: Check Non Refund Cancellation rate by Market Segment

In [ ]:
non_refund_segment = (
    df[df['deposit_type'] == 'Non Refund']
    .groupby('market_segment')['is_canceled']
    .agg(Booking = 'count',
         Cancelled = 'sum', 
         cancellation_rate = 'mean')
    .reset_index()
)

non_refund_segment['cancellation_rate'] = (
    non_refund_segment['cancellation_rate'] * 100
).round(2)

non_refund_segment.sort_values(
    'cancellation_rate',
    ascending=False
)

#### step 5: Check Non Refund Cancellation rate by Distribution Channel

In [ ]:
non_refund_channel = (
    df[df['deposit_type'] == 'Non Refund']
    .groupby('distribution_channel')['is_canceled']
    .agg(Booking = 'count',
         Cancelled = 'sum', 
         cancellation_rate = 'mean')
    .reset_index()
)

non_refund_channel['cancellation_rate'] = (
    non_refund_channel['cancellation_rate'] * 100
).round(2)

non_refund_channel.sort_values(
    'cancellation_rate',
    ascending=False
)

### Key finding
The 99.36% rate is supported by a substantial sample and remains exceptionally high across hotel types, market segments, and distribution channels, with the strongest concentration among TA/TO and Group bookings.

In [30]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

## Step 5: Cancellation Rate by Booking Channel

In [44]:
channel_cancellation = (
    df.groupby('distribution_channel')
        .agg(
            bookings = ('is_canceled','count'),
            cancelled = ('is_canceled','sum')
        )
        .reset_index()
)

channel_cancellation['not_cancelled'] = (
    channel_cancellation['bookings'] -
    channel_cancellation['cancelled']
)

channel_cancellation['cancellation_rate'] = (
    channel_cancellation['cancelled']
    / channel_cancellation['bookings']
    * 100
).round(2)

channel_cancellation = channel_cancellation.sort_values(
    'cancellation_rate',
    ascending= False
)
channel_cancellation

  distribution_channel  bookings  cancelled  not_cancelled  cancellation_rate
3                TA/TO     97729      40118          57611              41.05
0            Corporate      6491       1454           5037              22.40
2                  GDS       193         37            156              19.17
1               Direct     14483       2543          11940              17.56
4            Undefined         1          0              1               0.00

In [42]:
channel_cancellation

  distribution_channel  bookings  cancelled  not_cancelled  cancellation_rate
0            Corporate      6491       1454           5037              22.40
1               Direct     14483       2543          11940              17.56
2                  GDS       193         37            156              19.17
3                TA/TO     97729      40118          57611              41.05
4            Undefined         1          0              1               0.00